// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdp6xuEkz6NvPgtgI-Cbm7LOyaWXICoTI',
    appId: '1:26938537080:web:d8da70aadde2737c1ce98d',
    messagingSenderId: '26938537080',
    projectId: 'madad-app-notifications',
    authDomain: 'madad-app-notifications.firebaseapp.com',
    storageBucket: 'madad-app-notifications.firebasestorage.app',
    measurementId: 'G-1JJSFSZ8KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKqitPu-Qc58ed-eUri0hU2Uzy0pcACfA',
    appId: '1:26938537080:android:0a9a8e541a72ddab1ce98d',
    messagingSenderId: '26938537080',
    projectId: 'madad-app-notifications',
    storageBucket: 'madad-app-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJJ-e4LThISNoDg-LOZJsfJq-APN45grA',
    appId: '1:26938537080:ios:925c9f2d6cc0b91e1ce98d',
    messagingSenderId: '26938537080',
    projectId: 'madad-app-notifications',
    storageBucket: 'madad-app-notifications.firebasestorage.app',
    iosBundleId: 'com.example.madadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJJ-e4LThISNoDg-LOZJsfJq-APN45grA',
    appId: '1:26938537080:ios:925c9f2d6cc0b91e1ce98d',
    messagingSenderId: '26938537080',
    projectId: 'madad-app-notifications',
    storageBucket: 'madad-app-notifications.firebasestorage.app',
    iosBundleId: 'com.example.madadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdp6xuEkz6NvPgtgI-Cbm7LOyaWXICoTI',
    appId: '1:26938537080:web:5e61bea9e25cf3301ce98d',
    messagingSenderId: '26938537080',
    projectId: 'madad-app-notifications',
    authDomain: 'madad-app-notifications.firebaseapp.com',
    storageBucket: 'madad-app-notifications.firebasestorage.app',
    measurementId: 'G-0H1K81YH3C',
  );
}
