name: madad_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^17.1.0

  # State Management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # UI Components
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  lottie: ^3.0.0

  # Forms & Validation
  flutter_form_builder: ^10.3.0+2
  form_builder_validators: ^11.3.0

  # OTP / PIN Input
  pin_code_fields: ^9.1.0

  # Icons
  iconsax: ^0.0.8

  # Local Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600