name: madad_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # API
  http: ^1.2.0

  # store login token
  shared_preferences: ^2.2.3

  # state management
  provider: ^6.1.2

  # loading animations
  flutter_spinkit: ^5.2.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_full.png
    - assets/images/logo_hand.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/welcome_illustration.png
    - assets/images/nav_home.png
    - assets/images/nav_search.png
    - assets/images/nav_add.png
    - assets/images/nav_chat.png
    - assets/images/nav_profile.png
